# Generated by Django 4.2.25 on 2025-11-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'A'), ('AA', 'AA'), ('AAA', 'AAA')], max_length=3, unique=True, verbose_name='Tipo de Huevo')),
                ('precio_cubeta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Cubeta')),
                ('stock_cubetas', models.PositiveIntegerField(default=0, verbose_name='Stock en Cubetas')),
            ],
            options={
                'verbose_name': 'Tipo de Huevo',
                'verbose_name_plural': 'Tipos de Huevo',
                'ordering': ['tipo'],
            },
        ),
    ]
