# Generated by Django 4.2.25 on 2025-11-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('cedula_nit', models.CharField(max_length=20, unique=True, verbose_name='Cédula/NIT')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('latitud', models.FloatField(blank=True, help_text='Latitud de la ubicación del cliente', null=True, verbose_name='Latitud')),
                ('longitud', models.FloatField(blank=True, help_text='Longitud de la ubicación del cliente', null=True, verbose_name='Longitud')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
